<a href="https://colab.research.google.com/github/ChathuminiDisanayaka/Logistic-Regression/blob/main/03_Logistic_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
%matplotlib inline
#for mathematical functions
import numpy as np 
#plottting functions
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import normalize


In [ ]:
data = 'https://archive.ics.uci.edu/ml/machine-learning-databases/haberman/haberman.data'
data_df = pd.read_csv(data,header=None)
data_df



0   1  2  3
0    30  64  1  1
1    30  62  3  1
2    30  65  0  1
3    31  59  2  1
4    31  65  4  1
..   ..  .. .. ..
301  75  62  1  1
302  76  67  0  1
303  77  65  3  1
304  78  65  1  2
305  83  58  2  2

[306 rows x 4 columns]

In [ ]:
# input
x = data_df.iloc[:, [0,1,2]].values
print(x)
 
# output
y = data_df.iloc[:, 3].values
print(y)

[[30 64  1]
 [30 62  3]
 [30 65  0]
 [31 59  2]
 [31 65  4]
 [33 58 10]
 [33 60  0]
 [34 59  0]
 [34 66  9]
 [34 58 30]
 [34 60  1]
 [34 61 10]
 [34 67  7]
 [34 60  0]
 [35 64 13]
 [35 63  0]
 [36 60  1]
 [36 69  0]
 [37 60  0]
 [37 63  0]
 [37 58  0]
 [37 59  6]
 [37 60 15]
 [37 63  0]
 [38 69 21]
 [38 59  2]
 [38 60  0]
 [38 60  0]
 [38 62  3]
 [38 64  1]
 [38 66  0]
 [38 66 11]
 [38 60  1]
 [38 67  5]
 [39 66  0]
 [39 63  0]
 [39 67  0]
 [39 58  0]
 [39 59  2]
 [39 63  4]
 [40 58  2]
 [40 58  0]
 [40 65  0]
 [41 60 23]
 [41 64  0]
 [41 67  0]
 [41 58  0]
 [41 59  8]
 [41 59  0]
 [41 64  0]
 [41 69  8]
 [41 65  0]
 [41 65  0]
 [42 69  1]
 [42 59  0]
 [42 58  0]
 [42 60  1]
 [42 59  2]
 [42 61  4]
 [42 62 20]
 [42 65  0]
 [42 63  1]
 [43 58 52]
 [43 59  2]
 [43 64  0]
 [43 64  0]
 [43 63 14]
 [43 64  2]
 [43 64  3]
 [43 60  0]
 [43 63  2]
 [43 65  0]
 [43 66  4]
 [44 64  6]
 [44 58  9]
 [44 63 19]
 [44 61  0]
 [44 63  1]
 [44 61  0]
 [44 67 16]
 [45 65  6]
 [45 66  0]
 [45 67  1]
 [45

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state = 0)

from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
X_train = sc_x.fit_transform(X_train)
X_test = sc_x.transform(X_test)
 
print (X_train[0:10, :])

[[-1.09229448 -1.55391917 -0.53827882]
 [ 1.61641636 -1.55391917 -0.00810312]
 [ 0.86918578 -1.55391917 -0.53827882]
 [ 0.21535903  1.84688221 -0.14064705]
 [-1.37250594 -0.93559164 -0.53827882]
 [-0.06485244  0.3010634  -0.53827882]
 [ 1.14939725  1.22855468 -0.53827882]
 [-1.27910212 -1.55391917 -0.53827882]
 [-0.25166008  0.91939092 -0.40573489]
 [ 0.12195521 -1.24475541  0.38952865]]


In [ ]:
from sklearn.linear_model import LogisticRegression
#create the model
clsfier = LogisticRegression(random_state = 0)
clsfier.fit(X_train, y_train)

LogisticRegression(random_state=0)

In [ ]:
y_predict = clsfier.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score
print ("Accuracy : ", accuracy_score(y_test, y_predict))

Accuracy :  0.6103896103896104
